# You may do anything with this. It has no warranty.
# <https://creativecommons.org/publicdomain/zero/1.0/>
---
- hosts: all
  tasks:
    - name: ensure gpg agent is ready
      assert:
        that: "{{ 'gpg-preload.asc' | gpg_d }}"
      run_once: true
      delegate_to: localhost
